name: Build C++ EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cek file repository
        shell: powershell
        run: |
          Write-Host "=== DAFTAR FILE ==="
          Get-ChildItem -Recurse -File | Select-Object FullName

      - name: Cari file CPP
        shell: powershell
        run: |
          $cpp = Get-ChildItem -Recurse -Filter *.cpp | Select-Object -First 1

          if ($null -eq $cpp) {
              Write-Error "Tidak ditemukan file .cpp!"
              exit 1
          }

          Write-Host "File CPP ditemukan:"
          Write-Host $cpp.FullName

          g++ $cpp.FullName -o program.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: program.exe
